### ISSUE TITLE
Simulate creation of ldp binary

### ISSUE THREAD

**Issue by Stoff-Sebi** [Stoff-Sebi/spring-fedora#14]
### DESC
- create binaries like for datastreams on gams4

### TODOs
- [x] Resource model must contain mimetype
- [x] fix checking if datastream already exists
- [x] datastream must be linked to a digital object
- [x] add content to datastream!
- [ ] remove rdfxml field ?
- [ ] decide: resource must contain all available info? base rdf? AND additional datastreams? 
- [ ] add to ResourceReposiotry ability to create container types (handle via enum?)

**Comment by Stoff-Sebi** [comment]
implemented via adding Datastream as own domain model
