### ISSUE TITLE
Calls simple search API to display overview of objects?

### ISSUE THREAD

**Issue by Stoff-Sebi** [Stoff-Sebi/spring-fedora#18]
### DESC
- just to display on main page or something like that
- via: https://www.delftstack.com/howto/java/handling-json-arrays-in-java/

### TODOs
- [x] refactor: use spring env variables for fedora location (address + port)
- [x] add to DigitalObjectService
- [x] add to view part somewhere?
- [x] link from digital object overview to individual digital objects
- [x] add ability to delete digital objects
- [x] update initializing: creation of each object should be able to fail
- [ ] fully craft DigitalObjectRepository
- [x] fill in more stuff to the digital objects?
- [x] improve error handling
- [ ] think about: dto concept?

**Comment by Stoff-Sebi** [comment]
implemented / unnecessary
