### ISSUE TITLE
Clean up model classes

### ISSUE THREAD

**Issue by Stoff-Sebi** [Stoff-Sebi/spring-fedora#21]
### DESC
- clean up old and unused properties!

### TODOs
- [x] clean up resource + datastream fields
- [x] digital object should inherit from resource
- [x] correct view: show only datastream ids on digital object view

**Comment by Stoff-Sebi** [comment]
implemented
