### ISSUE TITLE
Implement some kind of content model workflow at object creation

### ISSUE THREAD

**Issue by Stoff-Sebi** [Stoff-Sebi/spring-fedora#22]
### DESC
- e.g. classes for ContentModel datastreams DC / TEI_SOURCE etc.? 
- craft content model workflow for gams
- add cm4f properties like on testserver

### TODOs
- [x] better utils location for mapPidToResourcePath!
- [x] implement DigitalObjectRepository (findById)
- [x] add to digital object service: createFromPrototype
- [x] compare with Johanneses impl / create own class for masrhalling etc.?
- [x] implement dublin core workflow?
- [x] think about adding more fields to DigitalObject fields?
- [x] implement
- [x] add to view ability to create object from prototype
- [x] digital object service: map model statements to prototype pids somewhere!

**Comment by Stoff-Sebi** [comment]
implemented
