### ISSUE TITLE
Implement transaction workflow

### ISSUE THREAD

**Issue by Stoff-Sebi** [Stoff-Sebi/spring-fedora#25]
### DESC
- take a look how transactions are managed on GAMS
- check how to adapt to Spring workflows?
- like here:  https://www.baeldung.com/spring-programmatic-transaction-management
- https://www.tutorialspoint.com/spring/spring_transaction_management.htm
- https://medium.com/javarevisited/spring-transaction-management-95ab4b2cf513
- https://www.youtube.com/results?search_query=spring+transactions

### TODOs
- [x] implement some kind of lambda functionaliy? so that no passing around of transaction ids is necessary
- [x] implement
- [x] import RepositoryUtils to append fedora response body if available to error messages
- [x] implement doGetTransaction() with correct error handling - txid better being an optional?  
- [x] Check on hot to handle if txid is null / optional / when transaction is expired or not!
- [x] Repository layer of fedora must grab transaction id from application / transaction context? 
- [x] injecting __own spring component as holder for transaction id__??
- [x] ~~implement FedoraHttpProxy as spring component~~ --> not necessary!
- [x] declutter service methods - being able to be transaction save = no intern method calls / using only from external instances injected by spring
- [x] update DigitalObjectRepository to work with transactions
- [x] deletion of datastreams must be transaction safe
- [x] update DatastreamRepository to work with transactions
- [x] update ResourceRepository to work with transactions
- [x] implement transaction save service layer!

**Comment by Stoff-Sebi** [comment]
implemented
