### ISSUE TITLE
Add bootstrap setup according to GAMS configuration

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/spring-fedora#3]
### DESC
- check which LDP containers need to be breated
- try to copy over code from Johannes (FedoraConnector init method?)

### TODOs
- [x] add fedora client to spring boot app
- [x] create bootstrap component as in rdf4j zimlab
- [x] think about: stored in fedora are resources AND containers --> is it truely a ResourceRepository?
- [x] check how to wrap code in some kind of fedora wrapper? services / repository layer? (I think fedora should work as DigitalObjectRepository? --- because fedora is something application dependent - spring should not know about fedora)
- [x] implement startup according to initial gams setup
