### ISSUE TITLE
Bootstraping: Create object prototypes

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/spring-fedora#4]
### DESC
- prototypes are not really something built-in in fedora. Are implemented via gams logic - "clone object"
- maybe play around with TEI or simple content models

### TODOs
- [x] add as empty containers
- [ ] think about: take over TransactionManager + FedoraProxy? (for adding some very basic RDF)
- [ ] implement TEI prototype with some basic RDF?
