### ISSUE TITLE
Add basic thymeleaf CRUD client functionality

### ISSUE THREAD

**Issue by Stoff-Sebi** [Stoff-Sebi/spring-fedora#9]
### DESC
- control via client basic opeartions

### TODOs
- [x] implement very basic search for objects via pid
- [x] add tymeleaf index html
- [x] implement create object form?
- [x] add link to fcrepo/rest  + apply two cols layout on main

**Comment by Stoff-Sebi** [comment]
implemented
